bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: MAV1/base_link
    odom_topic: /MAV1/odom
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: ""
    default_nav_through_poses_bt_xml: ""
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_pipeline_sequence_bt_node

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: progress_checker
    goal_checker_plugins: [goal_checker]
    controller_plugins: [FollowPath]
    progress_checker:
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.10
      movement_time_allowance: 10.0
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.20
      stateful: true
    FollowPath:
      plugin: dwb_core::DWBLocalPlanner
      debug_trajectory_details: false
      min_vel_x: -0.40
      max_vel_x: 0.40
      min_vel_y: -0.40
      max_vel_y: 0.40
      max_vel_theta: 0.80
      min_speed_xy: 0.0
      max_speed_xy: 0.50
      min_speed_theta: 0.0
      acc_lim_x: 0.50
      acc_lim_y: 0.50
      acc_lim_theta: 1.0
      decel_lim_x: -0.50
      decel_lim_y: -0.50
      decel_lim_theta: -1.0
      vx_samples: 12
      vy_samples: 12
      vtheta_samples: 16
      sim_time: 1.0
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.15
      trans_stopped_velocity: 0.05
      short_circuit_trajectory_evaluation: true
      stateful: true
      critics: [BaseObstacle, PathAlign, PathDist, GoalAlign, GoalDist, RotateToGoal]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalAlign.scale: 18.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 16.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: MAV1/base_link
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      update_frequency: 5.0
      publish_frequency: 2.0
      transform_tolerance: 0.2
      track_unknown_space: true
      robot_radius: 0.4
      plugins: [static_layer, inflation_layer]
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
        map_topic: /map
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        cost_scaling_factor: 3.0
        inflation_radius: 0.75
