<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drone_nav2_bringup</name>
  <version>0.1.0</version>
  <description>Launch and configuration package for MAV1 Nav2 integration.</description>
  <maintainer email="yuanyifan0625@gmail.com">Evan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_dwb_controller</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_navfn_planner</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>drone_nav2_apriltag</exec_depend>
  <exec_depend>drone_px4_nav2_bridge</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>action_msgs</test_depend>
  <test_depend>lifecycle_msgs</test_depend>
  <test_depend>nav2_msgs</test_depend>
  <test_depend>nav2_bt_navigator</test_depend>
  <test_depend>nav2_controller</test_depend>
  <test_depend>nav2_dwb_controller</test_depend>
  <test_depend>px4_msgs</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>rcl_interfaces</test_depend>
  <test_depend>rosgraph_msgs</test_depend>
  <test_depend>tf2_msgs</test_depend>
  <test_depend>visualization_msgs</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
