<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drone_px4_nav2_bridge</name>
  <version>0.1.0</version>
  <description>PX4-to-ROS bridge package for MAV1 Nav2 integration.</description>
  <maintainer email="yuanyifan0625@gmail.com">Evan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>px4_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>tf2_msgs</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
